-- 离谱法堂 V4：独立私密表与受控 RPC。不要修改或重跑 V2/V3/V3.1。
create table if not exists public.court_private_assignments (game_code text not null references public.games(code) on delete cascade, player_id text not null, round_no integer not null, keywords jsonb not null, primary key (game_code,player_id,round_no));
create table if not exists public.court_submissions (id text primary key, game_code text not null references public.games(code) on delete cascade, player_id text not null, round_no integer not null, defense text, supplement text, created_at timestamptz not null default now(), unique(game_code,player_id,round_no));
create table if not exists public.court_votes (game_code text not null references public.games(code) on delete cascade, player_id text not null, round_no integer not null, submission_ids jsonb not null, created_at timestamptz not null default now(), primary key(game_code,player_id,round_no));
alter table public.court_private_assignments enable row level security; alter table public.court_submissions enable row level security; alter table public.court_votes enable row level security;

create or replace function public.get_my_court_assignment(p_code text) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare v_player text; begin select player_id into v_player from public.game_members where game_code=upper(p_code) and user_uid=auth.uid(); if not found then raise exception 'not a room member'; end if; return coalesce((select jsonb_build_object('round',round_no,'keywords',keywords) from public.court_private_assignments where game_code=upper(p_code) and player_id=v_player order by round_no desc limit 1),'null'::jsonb); end $$;
create or replace function public.get_my_court_submission(p_code text) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare v_player text; begin select player_id into v_player from public.game_members where game_code=upper(p_code) and user_uid=auth.uid(); if not found then raise exception 'not a room member'; end if; return coalesce((select jsonb_build_object('submissionId',id,'round',round_no,'defense',defense,'supplement',supplement) from public.court_submissions where game_code=upper(p_code) and player_id=v_player order by round_no desc limit 1),'null'::jsonb); end $$;

create or replace function public.apply_court_action(p_code text,p_action_id text,p_action_type text,p_expected_status text,p_expected_round integer,p_expected_version bigint,p_payload jsonb default '{}'::jsonb) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare
 g public.games%rowtype; s jsonb; actor text; now_ms bigint := (extract(epoch from clock_timestamp())*1000)::bigint; ver bigint; rnd integer; deadline bigint; n integer; needed integer; text_value text; words jsonb; entries jsonb; expected jsonb; entry_ids jsonb; word text; pid text; rec record;
begin
 if auth.uid() is null then raise exception 'authentication required'; end if;
 if coalesce(length(trim(p_action_id)),0)<8 then raise exception 'invalid action id'; end if;
 select player_id into actor from public.game_members where game_code=upper(p_code) and user_uid=auth.uid(); if not found then raise exception 'not a room member'; end if;
 select * into g from public.games where code=upper(p_code) and expires_at>now() for update; if not found or g.state->>'gameType'<>'absurd_court' then raise exception 'court room not found'; end if; s:=g.state;
 if exists(select 1 from public.game_actions where game_code=g.code and action_id=p_action_id) then return jsonb_build_object('outcome','duplicate','code','ALREADY_APPLIED','message','操作已经完成','state',s,'version',g.version); end if;
 if p_expected_status is distinct from s->>'status' or p_expected_round is distinct from coalesce((s->>'round')::int,0) or p_expected_version is distinct from g.version then return jsonb_build_object('outcome','stale','code','STALE_STATE','message','状态已更新，请重试','state',s,'version',g.version); end if;
 rnd:=coalesce((s->>'round')::int,0); deadline:=coalesce((s->>'phaseDeadlineAt')::bigint,0);
 if p_action_type='start_court_game' then
   if s->>'status'<>'lobby' or s->>'ownerId'<>actor then raise exception 'only owner can start'; end if;
   select count(*) into n from jsonb_array_elements(s->'players') p where coalesce((p->>'alive')::boolean,true) and not coalesce((p->>'away')::boolean,false); if n<3 or n>8 then raise exception '需要 3–8 名在场成员'; end if;
   rnd:=1; select jsonb_agg(p->>'id') into expected from jsonb_array_elements(s->'players') p where coalesce((p->>'alive')::boolean,true) and not coalesce((p->>'away')::boolean,false);
   foreach pid in array array(select jsonb_array_elements_text(expected)) loop insert into public.court_private_assignments(game_code,player_id,round_no,keywords) values(g.code,pid,rnd,jsonb_build_array(case mod(length(pid),6) when 0 then '订书机' when 1 then '蓝牙' when 2 then '便利贴' when 3 then '投影仪' when 4 then '回形针' else '共享盘' end,case mod(length(pid),6) when 0 then '日历' when 1 then '白板' when 2 then '耳机' when 3 then '打印机' when 4 then '门禁' else '文件夹' end)); end loop;
   s:=jsonb_set(s,'{status}','"defense"'); s:=jsonb_set(s,'{round}',to_jsonb(rnd)); s:=jsonb_set(s,'{caseId}','"case-1"'); s:=jsonb_set(s,'{caseText}','"被控在领导宣布散会时，突然问了一句“还有吗？”。"'); s:=jsonb_set(s,'{expectedPlayerIds}',expected); s:=jsonb_set(s,'{phaseDeadlineAt}',to_jsonb(now_ms+30000)); s:=jsonb_set(s,'{defenseSubmittedCount}','0'); s:=jsonb_set(s,'{supplementSubmittedCount}','0'); s:=jsonb_set(s,'{voteSubmittedCount}','0'); s:=jsonb_set(s,'{publicEntries}','[]');
 elsif p_action_type='submit_court_defense' then
   if s->>'status'<>'defense' then raise exception 'wrong phase'; end if; text_value:=trim(coalesce(p_payload->>'defense','')); if length(text_value) not between 1 and 40 then raise exception '辩护须为 1–40 字'; end if;
   select keywords into words from public.court_private_assignments where game_code=g.code and player_id=actor and round_no=rnd; if words is null then raise exception '当前没有关键词'; end if; for word in select jsonb_array_elements_text(words) loop if position(word in text_value)=0 then raise exception '请包含两个关键词'; end if; end loop;
   insert into public.court_submissions(id,game_code,player_id,round_no,defense) values('s-'||actor||'-'||rnd,g.code,actor,rnd,text_value) on conflict(game_code,player_id,round_no) do nothing; select count(*) into n from public.court_submissions where game_code=g.code and round_no=rnd and defense is not null; s:=jsonb_set(s,'{defenseSubmittedCount}',to_jsonb(n));
 elsif p_action_type='submit_court_supplement' then
   if s->>'status'<>'supplement' then raise exception 'wrong phase'; end if; text_value:=trim(coalesce(p_payload->>'supplement','')); if length(text_value)>30 then raise exception '补充说明最多 30 字'; end if; update public.court_submissions set supplement=text_value where game_code=g.code and player_id=actor and round_no=rnd and defense is not null; if not found then raise exception '未提交辩护不能补充'; end if; select count(*) into n from public.court_submissions where game_code=g.code and round_no=rnd and supplement is not null; s:=jsonb_set(s,'{supplementSubmittedCount}',to_jsonb(n));
 elsif p_action_type='submit_court_vote' then
   if s->>'status'<>'voting' then raise exception 'wrong phase'; end if; entry_ids:=p_payload->'submissionIds'; needed:=case when jsonb_array_length(s->'expectedPlayerIds')>=5 then 2 else 1 end; if jsonb_typeof(entry_ids)<>'array' or jsonb_array_length(entry_ids)<>needed or (select count(distinct x) from jsonb_array_elements_text(entry_ids) x)<>needed then raise exception '请选择数量正确且不同的陈述'; end if; if exists(select 1 from jsonb_array_elements_text(entry_ids) x where x='s-'||actor||'-'||rnd or not exists(select 1 from public.court_submissions cs where cs.id=x and cs.game_code=g.code and cs.round_no=rnd)) then raise exception '不能投自己的陈述或无效陈述'; end if; insert into public.court_votes(game_code,player_id,round_no,submission_ids) values(g.code,actor,rnd,entry_ids) on conflict do nothing; select count(*) into n from public.court_votes where game_code=g.code and round_no=rnd; s:=jsonb_set(s,'{voteSubmittedCount}',to_jsonb(n));
 elsif p_action_type='advance_court_phase' then
   if s->>'status'='defense' then select count(*) into n from public.court_submissions where game_code=g.code and round_no=rnd and defense is not null; if n<jsonb_array_length(s->'expectedPlayerIds') and now_ms<deadline then raise exception 'still waiting'; end if; select coalesce(jsonb_agg(jsonb_build_object('submissionId',id,'displayCode','陈述 '||upper(left(md5(id),4)),'defense',defense,'supplement',null) order by md5(id)),'[]') into entries from public.court_submissions where game_code=g.code and round_no=rnd and defense is not null; s:=jsonb_set(s,'{publicEntries}',entries); s:=jsonb_set(s,'{status}','"defense_reveal"'); s:=jsonb_set(s,'{phaseDeadlineAt}',to_jsonb(now_ms+5000));
   elsif s->>'status'='defense_reveal' then if now_ms<deadline then raise exception 'still revealing'; end if; s:=jsonb_set(s,'{twistId}','"twist-1"'); s:=jsonb_set(s,'{twistText}','"新证据显示，监控录像与刚才的陈述存在明显差异。"'); s:=jsonb_set(s,'{status}','"supplement"'); s:=jsonb_set(s,'{phaseDeadlineAt}',to_jsonb(now_ms+15000));
   elsif s->>'status'='supplement' then if now_ms<deadline then raise exception 'still waiting'; end if; select coalesce(jsonb_agg(jsonb_build_object('submissionId',id,'displayCode','陈述 '||upper(left(md5(id),4)),'defense',defense,'supplement',nullif(supplement,'')) order by md5(id)),'[]') into entries from public.court_submissions where game_code=g.code and round_no=rnd and defense is not null; s:=jsonb_set(s,'{publicEntries}',entries); s:=jsonb_set(s,'{status}','"voting"'); s:=jsonb_set(s,'{phaseDeadlineAt}',to_jsonb(now_ms+30000));
   elsif s->>'status'='voting' then select count(*) into n from public.court_votes where game_code=g.code and round_no=rnd; if n<jsonb_array_length(s->'expectedPlayerIds') and now_ms<deadline then raise exception 'still waiting'; end if; for rec in select cs.player_id,count(*) as score from public.court_votes cv cross join jsonb_array_elements_text(cv.submission_ids) x join public.court_submissions cs on cs.id=x where cv.game_code=g.code and cv.round_no=rnd group by cs.player_id loop s:=jsonb_set(s,array['totalScores',rec.player_id],to_jsonb(coalesce((s->'totalScores'->>rec.player_id)::int,0)+rec.score),true); end loop; s:=jsonb_set(s,'{status}','"result"'); s:=jsonb_set(s,'{phaseDeadlineAt}',to_jsonb(now_ms+10000));
   elsif s->>'status'='result' then if now_ms<deadline then raise exception 'still showing result'; end if; if rnd>=3 then s:=jsonb_set(s,'{status}','"finished"'); s:=jsonb_set(s,'{phaseDeadlineAt}','null'); else rnd:=rnd+1; expected:=s->'expectedPlayerIds'; foreach pid in array array(select jsonb_array_elements_text(expected)) loop insert into public.court_private_assignments(game_code,player_id,round_no,keywords) values(g.code,pid,rnd,jsonb_build_array(case mod(length(pid)+rnd,6) when 0 then '订书机' when 1 then '蓝牙' when 2 then '便利贴' when 3 then '投影仪' when 4 then '回形针' else '共享盘' end,case mod(length(pid)+rnd,6) when 0 then '日历' when 1 then '白板' when 2 then '耳机' when 3 then '打印机' when 4 then '门禁' else '文件夹' end)); end loop; s:=jsonb_set(s,'{status}','"defense"'); s:=jsonb_set(s,'{round}',to_jsonb(rnd)); s:=jsonb_set(s,'{caseId}',to_jsonb('case-'||rnd)); s:=jsonb_set(s,'{caseText}',to_jsonb(case rnd when 2 then '被控将文件命名为“最终版_最终版2_这次真不改了.xlsx”。' else '被控对公司群通知使用“回复全部”，内容仅为“收到”。' end)); s:=jsonb_set(s,'{twistId}','null'); s:=jsonb_set(s,'{twistText}','null'); s:=jsonb_set(s,'{publicEntries}','[]'); s:=jsonb_set(s,'{defenseSubmittedCount}','0'); s:=jsonb_set(s,'{supplementSubmittedCount}','0'); s:=jsonb_set(s,'{voteSubmittedCount}','0'); s:=jsonb_set(s,'{phaseDeadlineAt}',to_jsonb(now_ms+30000)); end if;
   else raise exception 'nothing to advance'; end if;
 elsif p_action_type='end_court_game' then if s->>'ownerId'<>actor then raise exception 'only owner can end'; end if; s:=jsonb_set(s,'{status}','"finished"'); s:=jsonb_set(s,'{phaseDeadlineAt}','null');
 else raise exception 'unsupported court action'; end if;
 ver:=g.version+1; s:=jsonb_set(jsonb_set(s,'{version}',to_jsonb(ver)),'{updatedAt}',to_jsonb(now_ms)); update public.games set state=s,version=ver,updated_at=now() where code=g.code; insert into public.game_actions(game_code,action_id,actor_player_id,action_type,round_no,ballot_no,result) values(g.code,p_action_id,actor,p_action_type,coalesce((s->>'round')::int,0),0,jsonb_build_object('outcome','applied','code','OK')); return jsonb_build_object('outcome','applied','code','OK','message','操作成功','state',s,'version',ver);
end $$;
revoke all on public.court_private_assignments, public.court_submissions, public.court_votes from anon, authenticated;
revoke all on function public.get_my_court_assignment(text), public.get_my_court_submission(text), public.apply_court_action(text,text,text,text,integer,bigint,jsonb) from public;
grant execute on function public.get_my_court_assignment(text), public.get_my_court_submission(text), public.apply_court_action(text,text,text,text,integer,bigint,jsonb) to anon, authenticated;
