import { COURT_CASES, COURT_KEYWORDS, COURT_TWISTS } from './court-content.ts';
import { makeRoomCode, shuffle, type Player, type RandomSource } from './game.ts';

export type CourtStatus = 'lobby' | 'defense' | 'defense_reveal' | 'supplement' | 'voting' | 'result' | 'finished';
export interface CourtPublicEntry { submissionId: string; displayCode: string; defense: string; supplement: string | null; }
export interface CourtRoundResult { round: number; votes: Record<string, number>; winnerIds: string[]; }
export interface AbsurdCourtRoom { code: string; gameType: 'absurd_court'; ownerId: string; players: Player[]; playerLimit: number; version: number; createdAt: number; updatedAt: number; status: CourtStatus; round: number; totalRounds: 3; phaseDeadlineAt: number | null; caseId: string | null; caseText: string | null; twistId: string | null; twistText: string | null; usedCaseIds: string[]; usedTwistIds: string[]; expectedPlayerIds: string[]; defenseSubmittedCount: number; supplementSubmittedCount: number; voteSubmittedCount: number; publicEntries: CourtPublicEntry[]; roundResults: CourtRoundResult[]; totalScores: Record<string, number>; }
export const COURT_MIN_PLAYERS = 3, COURT_MAX_PLAYERS = 8;
export const COURT_DURATIONS: Record<Exclude<CourtStatus, 'lobby' | 'finished'>, number> = { defense: 30_000, defense_reveal: 5_000, supplement: 15_000, voting: 30_000, result: 10_000 };
export function createCourtRoom(ownerName: string, now = Date.now(), random: RandomSource = Math.random): AbsurdCourtRoom { const id = `p_${Math.floor(random()*1e12).toString(36)}`; return { code: makeRoomCode(random), gameType: 'absurd_court', ownerId: id, players:[{id,name:ownerName.trim() || '房主',seat:1,alive:true,cardReady:false}],playerLimit:COURT_MAX_PLAYERS,version:1,createdAt:now,updatedAt:now,status:'lobby',round:0,totalRounds:3,phaseDeadlineAt:null,caseId:null,caseText:null,twistId:null,twistText:null,usedCaseIds:[],usedTwistIds:[],expectedPlayerIds:[],defenseSubmittedCount:0,supplementSubmittedCount:0,voteSubmittedCount:0,publicEntries:[],roundResults:[],totalScores:{} }; }
export function courtVoteCount(players: number) { return players >= 5 ? 2 : 1; }
export function validateDefense(text: string, keywords: readonly string[]) { const clean = text.trim(); if (!clean || clean.length > 40) throw new Error('辩护须为 1–40 字'); const absent = keywords.filter(k => !clean.includes(k)); if (absent.length) throw new Error(`请包含关键词：${absent.join('、')}`); }
export function validateVote(voterSubmissionId: string | null, choices: string[], entryIds: string[], voters: number) { if (choices.length !== courtVoteCount(voters) || new Set(choices).size !== choices.length) throw new Error('请选择数量正确且不同的陈述'); if (choices.some(id => !entryIds.includes(id) || id === voterSubmissionId)) throw new Error('不能投给自己的陈述'); }
export function startCourtRound(room: AbsurdCourtRoom, now = Date.now(), random: RandomSource = Math.random): AbsurdCourtRoom { const expected = room.players.filter(p => p.alive && !p.away).map(p=>p.id); if (expected.length < COURT_MIN_PLAYERS) return {...room,status:'finished',phaseDeadlineAt:null,updatedAt:now,version:room.version+1}; const candidates = COURT_CASES.filter(c => !(room.usedCaseIds ?? []).includes(c.id)); const c = candidates[Math.floor(random()*candidates.length)] ?? COURT_CASES[0]; return {...room,status:'defense',round:room.round+1,caseId:c.id,caseText:c.text,twistId:null,twistText:null,usedCaseIds:[...(room.usedCaseIds ?? []),c.id],expectedPlayerIds:expected,defenseSubmittedCount:0,supplementSubmittedCount:0,voteSubmittedCount:0,publicEntries:[],phaseDeadlineAt:now+COURT_DURATIONS.defense,updatedAt:now,version:room.version+1}; }
export function nextCourtStatus(room: AbsurdCourtRoom, now = Date.now(), random: RandomSource = Math.random): AbsurdCourtRoom { const to = (status:CourtStatus, patch:Partial<AbsurdCourtRoom>={}) => ({...room,...patch,status,phaseDeadlineAt: status === 'finished' ? null : now + COURT_DURATIONS[status as keyof typeof COURT_DURATIONS],updatedAt:now,version:room.version+1}); if (room.status==='defense') return to('defense_reveal'); if (room.status==='defense_reveal') { const twists=COURT_TWISTS.filter(t => !(room.usedTwistIds ?? []).includes(t.id)); const t=twists[Math.floor(random()*twists.length)] ?? COURT_TWISTS[0]; return to('supplement',{twistId:t.id,twistText:t.text,usedTwistIds:[...(room.usedTwistIds ?? []),t.id]}); } if(room.status==='supplement') return to('voting'); if(room.status==='voting') return to('result'); if(room.status==='result') return room.round >= room.totalRounds ? to('finished') : startCourtRound(room,now,random); return room; }
export function assignKeywords(playerIds: string[], random: RandomSource = Math.random) { const words=shuffle(COURT_KEYWORDS,random).slice(0,playerIds.length*2); return Object.fromEntries(playerIds.map((id,index)=>[id,[words[index*2].text,words[index*2+1].text]])); }
export function rankScores(scores: Record<string,number>) { return Object.entries(scores).sort((a,b)=>b[1]-a[1]).map(([playerId,score],i,all)=>({playerId,score,rank:i>0 && score===all[i-1][1] ? all.findIndex(x=>x[1]===score)+1 : i+1})); }
