import test from 'node:test';
import assert from 'node:assert/strict';
import { COURT_CASES, COURT_KEYWORDS, COURT_TWISTS } from './court-content.ts';
import { assignKeywords, courtVoteCount, createCourtRoom, nextCourtStatus, rankScores, startCourtRound, validateDefense, validateVote } from './court-game.ts';

test('原创题库满足 20/30/60 且 ID 唯一', () => { for (const values of [COURT_CASES, COURT_TWISTS, COURT_KEYWORDS]) assert.equal(new Set(values.map(v=>v.id)).size, values.length); assert.ok(COURT_CASES.length >= 20 && COURT_TWISTS.length >= 30 && COURT_KEYWORDS.length >= 60); });
test('同轮关键词不重复，辩护必须同时包含两个关键词', () => { const assigned=assignKeywords(['a','b','c'],()=>.1); assert.equal(new Set(Object.values(assigned).flat()).size,6); assert.throws(()=>validateDefense('只有订书机',['订书机','蓝牙'])); assert.doesNotThrow(()=>validateDefense('订书机连上蓝牙后才发现问题',['订书机','蓝牙'])); });
test('同一局罪名与突发证据不重复', () => { let room=createCourtRoom('甲',0,()=>.1); room.players.push({id:'b',name:'乙',seat:2,alive:true,cardReady:false},{id:'c',name:'丙',seat:3,alive:true,cardReady:false}); room=startCourtRound(room,1,()=>.1); const firstCase=room.caseId; room=nextCourtStatus(room,2,()=>.1); room=nextCourtStatus(room,3,()=>.1); const firstTwist=room.twistId; room={...room,status:'result'}; room=nextCourtStatus(room,4,()=>.1); assert.notEqual(room.caseId,firstCase); room=nextCourtStatus({...room,status:'defense_reveal'},5,()=>.1); assert.notEqual(room.twistId,firstTwist); });
test('阶段可按系统时钟幂等推进并在三轮后结束', () => { let room=createCourtRoom('甲',0,()=>.2); room.players.push({id:'b',name:'乙',seat:2,alive:true,cardReady:false},{id:'c',name:'丙',seat:3,alive:true,cardReady:false}); room=startCourtRound(room,1,()=>.1); assert.equal(room.status,'defense'); room=nextCourtStatus(room,2,()=>.1); assert.equal(room.status,'defense_reveal'); room=nextCourtStatus(room,3,()=>.1); assert.equal(room.status,'supplement'); room={...room,status:'result',round:3}; assert.equal(nextCourtStatus(room,4).status,'finished'); });
test('投票禁止自投，5–8 人必须投两个不同陈述，平分共享名次', () => { assert.equal(courtVoteCount(3),1); assert.equal(courtVoteCount(5),2); assert.throws(()=>validateVote('a',['a'],['a','b','c'],3)); assert.throws(()=>validateVote('a',['b','b'],['a','b','c','d','e'],5)); assert.deepEqual(rankScores({a:4,b:4,c:2}).map(x=>x.rank),[1,1,3]); });
